### ISSUE TITLE
Test performance of IsFixed with CascadingValue

### ISSUE THREAD

**Issue by EdCharbeneau** [ivanchev/blazor-client-performance#2]
See: https://chrissainty.com/understanding-cascading-values-and-cascading-parameters/
```
<CascadingValue Value="@this" IsFixed="true">
```

What are the implications of adding this and needing to manage state changes manually.

**Comment by ivanchev** [comment]
If we force the state changes, there's no performance gains. And if we don't, the cells don't get updated when we need them to.
